spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**
        - id: messenger-service
          uri: http://localhost:8082
          predicates:
            - Path=/chats/**
        - id: user-service
          uri: http://localhost:8083
          predicates:
            - Path=/users/**
        - id: photo-service
          uri: http://localhost:8084
          predicates:
            - Path=/photos/**

server:
  port: 8080

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
