spring:
  application:
    name: profile
  datasource:
    url: jdbc:postgresql://localhost:5432/envelope_users
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8083