spring:
  application:
    name: chats
  data:
    mongodb:
      uri: mongodb://localhost:27017/messenger

server:
  port: 8082

logging:
  level:
    org.springframework.messaging: TRACE
    org.springframework.web.socket: TRACE
